name: example
description: Example for the dacros package
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  dacros:
    path: ../

dev_dependencies:
  build_runner: ^2.4.8
  lints: ^2.1.0
  test: ^1.24.0
