name: dacros
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.3 <4.0.0'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.1
dependencies:
  analyzer: ^6.3.0
  args: ^2.4.2
  build: ^2.4.1
  build_config: ^1.1.1
  collection: ^1.18.0
  source_gen: ^1.5.0
  yaml: ^3.1.2
